/**
 * Indicator catalog — extracted from the official Logística division catalog
 * (23 indicators, 50 fields, 239 rules) and narrowed to the eleven weekly ones
 * that apply to a warehouse operation.
 *
 * This is DATA, not code: the capture form is generated by reading this file.
 * Adding an indicator means adding an entry here, never writing JSX.
 *
 * Field ids, labels, help text and rule messages are kept verbatim from the
 * source catalog. The messages are written for the person doing the capture;
 * they are not reworded, not translated and not "improved".
 */

/** `BASE` is the formula's denominator; `NUMERATOR` goes on top. */
export type FieldRole = "BASE" | "NUMERATOR";

/** `COUNT` is whole units; `DECIMAL` allows fractions. */
export type FieldType = "COUNT" | "DECIMAL";

/** Which way is good for this indicator to move. Drives colour. */
export type Direction = "HIGHER_IS_BETTER" | "LOWER_IS_BETTER";

export interface Field {
  id: string;
  label: string;
  role: FieldRole;
  type: FieldType;
  unit: string | null;
  required: boolean;
  min: number | null;
  max: number | null;
  decimals: number;
  help: string | null;
}

/**
 * Field-scoped rules only — the ones that can be evaluated without a server.
 * They all reject: they blame the person capturing and are fixed on the spot.
 *
 * Submission-scoped rules (window, duplicate, variance, sender) escalate rather
 * than reject — they ask for a human decision and hold the submission — and
 * need an audit log plus an accepted previous period. Out of scope here.
 */
export interface Rule {
  id: string;
  fieldId: string;
  kind: "TYPE" | "RANGE" | "CONSISTENCY" | "NONZERO_BASE";
  expression: string;
  message: string;
}

export interface Indicator {
  id: string;
  name: string;
  domain: string;
  /** The formula in prose, as it comes from the catalog. Unsigned. */
  formula: string;
  direction: Direction;
  fields: Field[];
  rules: Rule[];
}

export const INDICATORS: Indicator[] = [
  {
    id: "L02",
    name: "Nivel de Servicio | Exactitud de Registro de Inventario (IRA)",
    domain: "Almacén",
    formula: "1- (ABS(Unidades Sobrantes - Unidades Faltantes) / Cantidad de Unidades contadas) * ABS: Absoluto faltante / Absoluto Sobrante (No negativos)",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L02_unidades_contadas",
        label: "Unidades contadas",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "La fórmula usa el valor absoluto de la diferencia entre sobrantes y faltantes sobre este total. Los sobrantes y los faltantes se capturan en positivo.",
      },
      {
        id: "C_L02_faltantes",
        label: "Faltantes",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L02 necesita. Fórmula oficial: 1- (ABS(Unidades Sobrantes - Unidades Faltantes) / Cantidad de Unidades contadas) * ABS: Absoluto faltante / Absoluto Sobrante (No negativos)",
      },
      {
        id: "C_L02_sobrantes",
        label: "Sobrantes",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L02 necesita. Fórmula oficial: 1- (ABS(Unidades Sobrantes - Unidades Faltantes) / Cantidad de Unidades contadas) * ABS: Absoluto faltante / Absoluto Sobrante (No negativos)",
      },
    ],
    rules: [
      {
        id: "R001",
        fieldId: "C_L02_unidades_contadas",
        kind: "TYPE",
        expression: "entero",
        message: "«Unidades contadas» se captura como un número entero.",
      },
      {
        id: "R002",
        fieldId: "C_L02_unidades_contadas",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Unidades contadas» no puede ser negativo.",
      },
      {
        id: "R003",
        fieldId: "C_L02_faltantes",
        kind: "TYPE",
        expression: "entero",
        message: "«Faltantes» se captura como un número entero.",
      },
      {
        id: "R004",
        fieldId: "C_L02_faltantes",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Faltantes» no puede ser negativo.",
      },
      {
        id: "R005",
        fieldId: "C_L02_sobrantes",
        kind: "TYPE",
        expression: "entero",
        message: "«Sobrantes» se captura como un número entero.",
      },
      {
        id: "R006",
        fieldId: "C_L02_sobrantes",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Sobrantes» no puede ser negativo.",
      },
      {
        id: "R007",
        fieldId: "C_L02_faltantes",
        kind: "CONSISTENCY",
        expression: "C_L02_faltantes <= C_L02_unidades_contadas",
        message: "«Faltantes» no puede ser mayor que «Unidades contadas»: la parte no supera al total.",
      },
      {
        id: "R008",
        fieldId: "C_L02_sobrantes",
        kind: "CONSISTENCY",
        expression: "C_L02_sobrantes <= C_L02_unidades_contadas",
        message: "«Sobrantes» no puede ser mayor que «Unidades contadas»: la parte no supera al total.",
      },
      {
        id: "R009",
        fieldId: "C_L02_unidades_contadas",
        kind: "NONZERO_BASE",
        expression: "C_L02_unidades_contadas > 0",
        message: "«Unidades contadas» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L11",
    name: "Cobertura de Plantilla Operativa",
    domain: "Capital humano",
    formula: "1 - (Vacantes de Personal / Requerimiento Aprobado de Personal)",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L11_vacantes_de_personal",
        label: "Vacantes de personal",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "personas",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L11 necesita. Fórmula oficial: 1 - (Vacantes de Personal / Requerimiento Aprobado de Personal)",
      },
      {
        id: "C_L11_requerimiento_aprobado",
        label: "Requerimiento aprobado",
        role: "BASE",
        type: "COUNT",
        unit: "personas",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L11 necesita. Fórmula oficial: 1 - (Vacantes de Personal / Requerimiento Aprobado de Personal)",
      },
    ],
    rules: [
      {
        id: "R027",
        fieldId: "C_L11_vacantes_de_personal",
        kind: "TYPE",
        expression: "entero",
        message: "«Vacantes de personal» se captura como un número entero.",
      },
      {
        id: "R028",
        fieldId: "C_L11_vacantes_de_personal",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Vacantes de personal» no puede ser negativo.",
      },
      {
        id: "R029",
        fieldId: "C_L11_requerimiento_aprobado",
        kind: "TYPE",
        expression: "entero",
        message: "«Requerimiento aprobado» se captura como un número entero.",
      },
      {
        id: "R030",
        fieldId: "C_L11_requerimiento_aprobado",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Requerimiento aprobado» no puede ser negativo.",
      },
      {
        id: "R031",
        fieldId: "C_L11_vacantes_de_personal",
        kind: "CONSISTENCY",
        expression: "C_L11_vacantes_de_personal <= C_L11_requerimiento_aprobado",
        message: "«Vacantes de personal» no puede ser mayor que «Requerimiento aprobado»: la parte no supera al total.",
      },
      {
        id: "R032",
        fieldId: "C_L11_requerimiento_aprobado",
        kind: "NONZERO_BASE",
        expression: "C_L11_requerimiento_aprobado > 0",
        message: "«Requerimiento aprobado» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L15",
    name: "Aprovechamiento de activos |%Vacancy (m2)",
    domain: "Almacén",
    formula: "Metros cuadrados disponibles / Metros cuadrados totales",
    direction: "LOWER_IS_BETTER",
    fields: [
      {
        id: "C_L15_metros_cuadrados_disponibles",
        label: "Metros cuadrados disponibles",
        role: "NUMERATOR",
        type: "DECIMAL",
        unit: "m²",
        required: true,
        min: 0,
        max: null,
        decimals: 2,
        help: "Dato que la fórmula de L15 necesita. Fórmula oficial: Metros cuadrados disponibles / Metros cuadrados totales",
      },
      {
        id: "C_L15_metros_cuadrados_totales",
        label: "Metros cuadrados totales",
        role: "BASE",
        type: "DECIMAL",
        unit: "m²",
        required: true,
        min: 0,
        max: null,
        decimals: 2,
        help: "Dato que la fórmula de L15 necesita. Fórmula oficial: Metros cuadrados disponibles / Metros cuadrados totales",
      },
    ],
    rules: [
      {
        id: "R063",
        fieldId: "C_L15_metros_cuadrados_disponibles",
        kind: "TYPE",
        expression: "decimal(2)",
        message: "«Metros cuadrados disponibles» se captura como un número con decimales.",
      },
      {
        id: "R064",
        fieldId: "C_L15_metros_cuadrados_disponibles",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Metros cuadrados disponibles» no puede ser negativo.",
      },
      {
        id: "R065",
        fieldId: "C_L15_metros_cuadrados_totales",
        kind: "TYPE",
        expression: "decimal(2)",
        message: "«Metros cuadrados totales» se captura como un número con decimales.",
      },
      {
        id: "R066",
        fieldId: "C_L15_metros_cuadrados_totales",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Metros cuadrados totales» no puede ser negativo.",
      },
      {
        id: "R067",
        fieldId: "C_L15_metros_cuadrados_disponibles",
        kind: "CONSISTENCY",
        expression: "C_L15_metros_cuadrados_disponibles <= C_L15_metros_cuadrados_totales",
        message: "«Metros cuadrados disponibles» no puede ser mayor que «Metros cuadrados totales»: la parte no supera al total.",
      },
      {
        id: "R068",
        fieldId: "C_L15_metros_cuadrados_totales",
        kind: "NONZERO_BASE",
        expression: "C_L15_metros_cuadrados_totales > 0",
        message: "«Metros cuadrados totales» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L30",
    name: "% Tiempo Extra (Origen Traxion)",
    domain: "Capital humano",
    formula: "Horas Extra Empresa / Horas Laboradas Horas Extra Empresa = Horas Extra Doble Empresa + Horas Extra Triple Empresa Horas Laboradas = Horas Extra Empresa + Horas Laboradas Normales",
    direction: "LOWER_IS_BETTER",
    fields: [
      {
        id: "C_L30_horas_extra_dobles",
        label: "Horas extra dobles",
        role: "NUMERATOR",
        type: "DECIMAL",
        unit: "horas",
        required: true,
        min: 0,
        max: null,
        decimals: 2,
        help: "Dato que la fórmula de L30 necesita. Fórmula oficial: Horas Extra Empresa / Horas Laboradas Horas Extra Empresa = Horas Extra Doble Empresa + Horas Extra Triple Empresa Horas Laboradas = Horas Extra Empre",
      },
      {
        id: "C_L30_horas_extra_triples",
        label: "Horas extra triples",
        role: "NUMERATOR",
        type: "DECIMAL",
        unit: "horas",
        required: true,
        min: 0,
        max: null,
        decimals: 2,
        help: "Dato que la fórmula de L30 necesita. Fórmula oficial: Horas Extra Empresa / Horas Laboradas Horas Extra Empresa = Horas Extra Doble Empresa + Horas Extra Triple Empresa Horas Laboradas = Horas Extra Empre",
      },
      {
        id: "C_L30_horas_laboradas_normales",
        label: "Horas laboradas normales",
        role: "BASE",
        type: "DECIMAL",
        unit: "horas",
        required: true,
        min: 0,
        max: null,
        decimals: 2,
        help: "La fórmula suma a estas horas las extra dobles y triples para formar el total contra el que se divide.",
      },
    ],
    rules: [
      {
        id: "R089",
        fieldId: "C_L30_horas_extra_dobles",
        kind: "TYPE",
        expression: "decimal(2)",
        message: "«Horas extra dobles» se captura como un número con decimales.",
      },
      {
        id: "R090",
        fieldId: "C_L30_horas_extra_dobles",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Horas extra dobles» no puede ser negativo.",
      },
      {
        id: "R091",
        fieldId: "C_L30_horas_extra_triples",
        kind: "TYPE",
        expression: "decimal(2)",
        message: "«Horas extra triples» se captura como un número con decimales.",
      },
      {
        id: "R092",
        fieldId: "C_L30_horas_extra_triples",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Horas extra triples» no puede ser negativo.",
      },
      {
        id: "R093",
        fieldId: "C_L30_horas_laboradas_normales",
        kind: "TYPE",
        expression: "decimal(2)",
        message: "«Horas laboradas normales» se captura como un número con decimales.",
      },
      {
        id: "R094",
        fieldId: "C_L30_horas_laboradas_normales",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Horas laboradas normales» no puede ser negativo.",
      },
      {
        id: "R095",
        fieldId: "C_L30_horas_extra_dobles",
        kind: "CONSISTENCY",
        expression: "C_L30_horas_extra_dobles <= C_L30_horas_laboradas_normales",
        message: "«Horas extra dobles» no puede ser mayor que «Horas laboradas normales»: la parte no supera al total.",
      },
      {
        id: "R096",
        fieldId: "C_L30_horas_extra_triples",
        kind: "CONSISTENCY",
        expression: "C_L30_horas_extra_triples <= C_L30_horas_laboradas_normales",
        message: "«Horas extra triples» no puede ser mayor que «Horas laboradas normales»: la parte no supera al total.",
      },
      {
        id: "R097",
        fieldId: "C_L30_horas_laboradas_normales",
        kind: "NONZERO_BASE",
        expression: "C_L30_horas_laboradas_normales > 0",
        message: "«Horas laboradas normales» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L37",
    name: "Exactitud de Existencias de Inventario (ILA)",
    domain: "Almacén",
    formula: "1 - (Ubicaciones con error / Ubicaciones auditadas)",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L37_ubicaciones_auditadas",
        label: "Ubicaciones auditadas",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L37 necesita. Fórmula oficial: 1 - (Ubicaciones con error / Ubicaciones auditadas)",
      },
      {
        id: "C_L37_ubicaciones_con_error",
        label: "Ubicaciones con error",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L37 necesita. Fórmula oficial: 1 - (Ubicaciones con error / Ubicaciones auditadas)",
      },
    ],
    rules: [
      {
        id: "R108",
        fieldId: "C_L37_ubicaciones_auditadas",
        kind: "TYPE",
        expression: "entero",
        message: "«Ubicaciones auditadas» se captura como un número entero.",
      },
      {
        id: "R109",
        fieldId: "C_L37_ubicaciones_auditadas",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Ubicaciones auditadas» no puede ser negativo.",
      },
      {
        id: "R110",
        fieldId: "C_L37_ubicaciones_con_error",
        kind: "TYPE",
        expression: "entero",
        message: "«Ubicaciones con error» se captura como un número entero.",
      },
      {
        id: "R111",
        fieldId: "C_L37_ubicaciones_con_error",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Ubicaciones con error» no puede ser negativo.",
      },
      {
        id: "R112",
        fieldId: "C_L37_ubicaciones_con_error",
        kind: "CONSISTENCY",
        expression: "C_L37_ubicaciones_con_error <= C_L37_ubicaciones_auditadas",
        message: "«Ubicaciones con error» no puede ser mayor que «Ubicaciones auditadas»: la parte no supera al total.",
      },
      {
        id: "R113",
        fieldId: "C_L37_ubicaciones_auditadas",
        kind: "NONZERO_BASE",
        expression: "C_L37_ubicaciones_auditadas > 0",
        message: "«Ubicaciones auditadas» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L38",
    name: "Cumplimiento al plan de descarga",
    domain: "Almacén",
    formula: "Descargas en Tiempo / Descargas Totales",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L38_descargas_en_tiempo",
        label: "Descargas en tiempo",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L38 necesita. Fórmula oficial: Descargas en Tiempo / Descargas Totales",
      },
      {
        id: "C_L38_descargas_totales",
        label: "Descargas totales",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L38 necesita. Fórmula oficial: Descargas en Tiempo / Descargas Totales",
      },
    ],
    rules: [
      {
        id: "R118",
        fieldId: "C_L38_descargas_en_tiempo",
        kind: "TYPE",
        expression: "entero",
        message: "«Descargas en tiempo» se captura como un número entero.",
      },
      {
        id: "R119",
        fieldId: "C_L38_descargas_en_tiempo",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Descargas en tiempo» no puede ser negativo.",
      },
      {
        id: "R120",
        fieldId: "C_L38_descargas_totales",
        kind: "TYPE",
        expression: "entero",
        message: "«Descargas totales» se captura como un número entero.",
      },
      {
        id: "R121",
        fieldId: "C_L38_descargas_totales",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Descargas totales» no puede ser negativo.",
      },
      {
        id: "R122",
        fieldId: "C_L38_descargas_en_tiempo",
        kind: "CONSISTENCY",
        expression: "C_L38_descargas_en_tiempo <= C_L38_descargas_totales",
        message: "«Descargas en tiempo» no puede ser mayor que «Descargas totales»: la parte no supera al total.",
      },
      {
        id: "R123",
        fieldId: "C_L38_descargas_totales",
        kind: "NONZERO_BASE",
        expression: "C_L38_descargas_totales > 0",
        message: "«Descargas totales» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L39",
    name: "Cumplimiento al plan de carga",
    domain: "Almacén",
    formula: "Cargas en Tiempo / Cargas Totales",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L39_cargas_en_tiempo",
        label: "Cargas en tiempo",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L39 necesita. Fórmula oficial: Cargas en Tiempo / Cargas Totales",
      },
      {
        id: "C_L39_cargas_totales",
        label: "Cargas totales",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L39 necesita. Fórmula oficial: Cargas en Tiempo / Cargas Totales",
      },
    ],
    rules: [
      {
        id: "R128",
        fieldId: "C_L39_cargas_en_tiempo",
        kind: "TYPE",
        expression: "entero",
        message: "«Cargas en tiempo» se captura como un número entero.",
      },
      {
        id: "R129",
        fieldId: "C_L39_cargas_en_tiempo",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Cargas en tiempo» no puede ser negativo.",
      },
      {
        id: "R130",
        fieldId: "C_L39_cargas_totales",
        kind: "TYPE",
        expression: "entero",
        message: "«Cargas totales» se captura como un número entero.",
      },
      {
        id: "R131",
        fieldId: "C_L39_cargas_totales",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Cargas totales» no puede ser negativo.",
      },
      {
        id: "R132",
        fieldId: "C_L39_cargas_en_tiempo",
        kind: "CONSISTENCY",
        expression: "C_L39_cargas_en_tiempo <= C_L39_cargas_totales",
        message: "«Cargas en tiempo» no puede ser mayor que «Cargas totales»: la parte no supera al total.",
      },
      {
        id: "R133",
        fieldId: "C_L39_cargas_totales",
        kind: "NONZERO_BASE",
        expression: "C_L39_cargas_totales > 0",
        message: "«Cargas totales» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L42",
    name: "% Incidencias y reclamaciones",
    domain: "Almacén",
    formula: "Total de incidencias y reclamaciones (empresa+cliente) / Notas embarcadas",
    direction: "LOWER_IS_BETTER",
    fields: [
      {
        id: "C_L42_incidencias_y_reclamaciones",
        label: "Incidencias y reclamaciones",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L42 necesita. Fórmula oficial: Total de incidencias y reclamaciones (empresa+cliente) / Notas embarcadas",
      },
      {
        id: "C_L42_notas_embarcadas",
        label: "Notas embarcadas",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L42 necesita. Fórmula oficial: Total de incidencias y reclamaciones (empresa+cliente) / Notas embarcadas",
      },
    ],
    rules: [
      {
        id: "R138",
        fieldId: "C_L42_incidencias_y_reclamaciones",
        kind: "TYPE",
        expression: "entero",
        message: "«Incidencias y reclamaciones» se captura como un número entero.",
      },
      {
        id: "R139",
        fieldId: "C_L42_incidencias_y_reclamaciones",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Incidencias y reclamaciones» no puede ser negativo.",
      },
      {
        id: "R140",
        fieldId: "C_L42_notas_embarcadas",
        kind: "TYPE",
        expression: "entero",
        message: "«Notas embarcadas» se captura como un número entero.",
      },
      {
        id: "R141",
        fieldId: "C_L42_notas_embarcadas",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Notas embarcadas» no puede ser negativo.",
      },
      {
        id: "R142",
        fieldId: "C_L42_incidencias_y_reclamaciones",
        kind: "CONSISTENCY",
        expression: "C_L42_incidencias_y_reclamaciones <= C_L42_notas_embarcadas",
        message: "«Incidencias y reclamaciones» no puede ser mayor que «Notas embarcadas»: la parte no supera al total.",
      },
      {
        id: "R143",
        fieldId: "C_L42_notas_embarcadas",
        kind: "NONZERO_BASE",
        expression: "C_L42_notas_embarcadas > 0",
        message: "«Notas embarcadas» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L58",
    name: "Dock to Delivery o Dock to Stock",
    domain: "Almacén",
    formula: "ID's on time / ID's de recibo",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L58_id_s_on_time",
        label: "ID's on time",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L58 necesita. Fórmula oficial: ID's on time / ID's de recibo",
      },
      {
        id: "C_L58_id_s_de_recibo",
        label: "ID's de recibo",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L58 necesita. Fórmula oficial: ID's on time / ID's de recibo",
      },
    ],
    rules: [
      {
        id: "R174",
        fieldId: "C_L58_id_s_on_time",
        kind: "TYPE",
        expression: "entero",
        message: "«ID's on time» se captura como un número entero.",
      },
      {
        id: "R175",
        fieldId: "C_L58_id_s_on_time",
        kind: "RANGE",
        expression: ">= 0",
        message: "«ID's on time» no puede ser negativo.",
      },
      {
        id: "R176",
        fieldId: "C_L58_id_s_de_recibo",
        kind: "TYPE",
        expression: "entero",
        message: "«ID's de recibo» se captura como un número entero.",
      },
      {
        id: "R177",
        fieldId: "C_L58_id_s_de_recibo",
        kind: "RANGE",
        expression: ">= 0",
        message: "«ID's de recibo» no puede ser negativo.",
      },
      {
        id: "R178",
        fieldId: "C_L58_id_s_on_time",
        kind: "CONSISTENCY",
        expression: "C_L58_id_s_on_time <= C_L58_id_s_de_recibo",
        message: "«ID's on time» no puede ser mayor que «ID's de recibo»: la parte no supera al total.",
      },
      {
        id: "R179",
        fieldId: "C_L58_id_s_de_recibo",
        kind: "NONZERO_BASE",
        expression: "C_L58_id_s_de_recibo > 0",
        message: "«ID's de recibo» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L64",
    name: "Precisión de Escaneos (SSP)",
    domain: "Almacén",
    formula: "Escaneo Interno / Escaneo Amazon",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L64_escaneo_interno",
        label: "Escaneo interno",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L64 necesita. Fórmula oficial: Escaneo Interno / Escaneo Amazon",
      },
      {
        id: "C_L64_escaneo_amazon",
        label: "Escaneo Amazon",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L64 necesita. Fórmula oficial: Escaneo Interno / Escaneo Amazon",
      },
    ],
    rules: [
      {
        id: "R197",
        fieldId: "C_L64_escaneo_interno",
        kind: "TYPE",
        expression: "entero",
        message: "«Escaneo interno» se captura como un número entero.",
      },
      {
        id: "R198",
        fieldId: "C_L64_escaneo_interno",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Escaneo interno» no puede ser negativo.",
      },
      {
        id: "R199",
        fieldId: "C_L64_escaneo_amazon",
        kind: "TYPE",
        expression: "entero",
        message: "«Escaneo Amazon» se captura como un número entero.",
      },
      {
        id: "R200",
        fieldId: "C_L64_escaneo_amazon",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Escaneo Amazon» no puede ser negativo.",
      },
      {
        id: "R201",
        fieldId: "C_L64_escaneo_interno",
        kind: "CONSISTENCY",
        expression: "C_L64_escaneo_interno <= C_L64_escaneo_amazon",
        message: "«Escaneo interno» no puede ser mayor que «Escaneo Amazon»: la parte no supera al total.",
      },
      {
        id: "R202",
        fieldId: "C_L64_escaneo_amazon",
        kind: "NONZERO_BASE",
        expression: "C_L64_escaneo_amazon > 0",
        message: "«Escaneo Amazon» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
  {
    id: "L67",
    name: "Nivel de Servicio | Tasa de Servicios Perfectos (POF)",
    domain: "Almacén",
    formula: "Pedidos perfectos / Pedidos Totales",
    direction: "HIGHER_IS_BETTER",
    fields: [
      {
        id: "C_L67_pedidos_perfectos",
        label: "Pedidos perfectos",
        role: "NUMERATOR",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L67 necesita. Fórmula oficial: Pedidos perfectos / Pedidos Totales",
      },
      {
        id: "C_L67_pedidos_totales",
        label: "Pedidos totales",
        role: "BASE",
        type: "COUNT",
        unit: "unidades",
        required: true,
        min: 0,
        max: null,
        decimals: 0,
        help: "Dato que la fórmula de L67 necesita. Fórmula oficial: Pedidos perfectos / Pedidos Totales",
      },
    ],
    rules: [
      {
        id: "R207",
        fieldId: "C_L67_pedidos_perfectos",
        kind: "TYPE",
        expression: "entero",
        message: "«Pedidos perfectos» se captura como un número entero.",
      },
      {
        id: "R208",
        fieldId: "C_L67_pedidos_perfectos",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Pedidos perfectos» no puede ser negativo.",
      },
      {
        id: "R209",
        fieldId: "C_L67_pedidos_totales",
        kind: "TYPE",
        expression: "entero",
        message: "«Pedidos totales» se captura como un número entero.",
      },
      {
        id: "R210",
        fieldId: "C_L67_pedidos_totales",
        kind: "RANGE",
        expression: ">= 0",
        message: "«Pedidos totales» no puede ser negativo.",
      },
      {
        id: "R211",
        fieldId: "C_L67_pedidos_perfectos",
        kind: "CONSISTENCY",
        expression: "C_L67_pedidos_perfectos <= C_L67_pedidos_totales",
        message: "«Pedidos perfectos» no puede ser mayor que «Pedidos totales»: la parte no supera al total.",
      },
      {
        id: "R212",
        fieldId: "C_L67_pedidos_totales",
        kind: "NONZERO_BASE",
        expression: "C_L67_pedidos_totales > 0",
        message: "«Pedidos totales» es la base del cálculo: con cero, el indicador no se puede calcular.",
      },
    ],
  },
];

/** Every field of the eleven indicators, in capture order. */
export const FIELDS: Field[] = INDICATORS.flatMap((i) => i.fields);

export const INDICATOR_COUNT = INDICATORS.length;
export const FIELD_COUNT = FIELDS.length;

export function getIndicator(id: string): Indicator | undefined {
  return INDICATORS.find((i) => i.id === id);
}
